default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV.fetch("DB_HOST", "db") %>
  database: <%= ENV.fetch("DB_NAME", "app_development") %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>

test:
  <<: *default
  host: <%= ENV.fetch("DB_HOST", "db") %>
  database: <%= ENV.fetch("DB_NAME_TEST", "app_test") %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  host: <%= ENV.fetch("DB_HOST", "enhance-reading-app-db.flycast") %>
